import type { Metadata } from 'next';

import './globals.css';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { twMerge } from 'tailwind-merge';

import { Providers } from '@/providers/Providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const inter = Inter({
    subsets: ['latin'],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={`h-full antialiased`}>
            <body className={twMerge('min-h-full flex flex-col', inter.className)}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
