"""add resend cooldown to pending registrations

Revision ID: eded9d2eea01
Revises: 02015bdf581b
Create Date: 2026-05-08 14:47:27.806330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eded9d2eea01'
down_revision: Union[str, Sequence[str], None] = '02015bdf581b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registrations', sa.Column('resend_available_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_registrations', 'resend_available_at')
    # ### end Alembic commands ###
